### ISSUE TITLE
Avoid mutating the source array

### ISSUE THREAD

**Issue by bigopon** [shahabganji/aurelia-toolbelt#30]
Example:

https://github.com/shahabganji/aurelia-toolbelt/blob/6a01114cfa8e1e211adb3b348e613d924df71001/src/value-converters/purejs/array/order-by.ts#L14

This is a dangerous operation, two bindings using sort targeting the same array will cause infinite loop. I think it's more natural to have mutable op but we have to stick to immutability.

**Comment by shahabganji** [comment]
@bigopon 
You are totally right, I am just copied this from somewhere, our main focus is now on ```bootstrap``` and when it reaches a stable part we will come back on value-converters.

**Comment by shahabganji** [comment]
@bigopon 

https://github.com/shahabganji/aurelia-toolbelt/blob/6a01114cfa8e1e211adb3b348e613d924df71001/src/value-converters/purejs/array/order-by.ts#L7

isn't this: :point_up_2: stick to immutability?

**Comment by bigopon** [comment]
Yes that should be it
