### ISSUE TITLE
abt-navbar, fixed-top

### ISSUE THREAD

**Issue by shahabganji** [shahabganji/aurelia-toolbelt#46]
When we add ```.fixed-top``` to the ```abt-navbar```, and then clicking on ```bt-navbar-dropdown-mega-item``` there is a gap between navbar and items to be shown.

**Comment by HamedFathi** [comment]
Bootstrap default behavior [sample](https://jsfiddle.net/ymzkna50/1/)

Who exactly does a navbar down? Do not you think this feature is more for use as a footer?

**Comment by HamedFathi** [comment]
I need more time for investigation, this gap is because of supporting megamenu beside standard navbar.
We have two choices:
1. Separate navbar and mega menu.
2. Find a way to calculating correct top for content.

**Comment by shahabganji** [comment]
we can get into details later on.
