### ISSUE TITLE
abt-navbar-dropdown, placements?

### ISSUE THREAD

**Issue by shahabganji** [shahabganji/aurelia-toolbelt#47]
How to change the placement of dropdown opener to top or bottom. The default behaviour is bottom; however, when setting the navbar to fixed at the bottom of the page, I expect the dropdown to be opened upward.
```html
<abt-navbar class="fixed-bottom" style="z-index:1021" class="bg-light">
...
...
</abt-navbar>
```

<img width="1436" alt="screen shot 2018-01-28 at 22 19 00" src="https://user-images.githubusercontent.com/4405518/35485764-489162ca-0479-11e8-9276-4f693bf667f5.png">

**Comment by HamedFathi** [comment]
Bootstrap default behavior [sample](https://jsfiddle.net/ymzkna50/1/)

Who exactly does a navbar down as menu?! I think this feature is more for use as a footer.

**Comment by HamedFathi** [comment]
Now, You can use this
```
<abt-navbar-dropdown placement="up" title="DropDown">
```
