### ISSUE TITLE
Demo page - Uncaught package error

### ISSUE THREAD

**Issue by freshcutdevelopment** [shahabganji/aurelia-toolbelt#48]
Great work on the toolbelt so far! 👍 

I just went to visit the demo page and noticed that there is an error on page initialization preventing the page from loading:

`Uncaught Package not found fuse-box-aurelia-loader`

Maybe worth taking a look if you're not aware of it already 😄 .

Keep up the great work.

Cheers,
Sean

**Comment by shahabganji** [comment]
Dear @freshcutdevelopment,

I'm afraid we are aware of the issue you mentioned; :wink:  that is owing to the fact that our previous demo page was an eyesore :smile:, so we stopped the application on the landing page, preventing the app to start.

We will upload the new demo page tonight approx. 24:00 ( IRIST ), in which most of the components have better demos and documentation, we will also let those components working properly but not documented yet to be available in the demo. 

Worth to mention that we will release a ```beta.1``` version as soon as the documentation for **all** the components( including bootstrap, value-converters, and other non-bootstrap UI components ) were ready, both on ```npm``` and demo.

Cheers,
Shahab

**Comment by shahabganji** [comment]
Just to make sure, may I ask you ( @freshcutdevelopment  ) to tell us which browser and OS you were using?

**Comment by freshcutdevelopment** [comment]
Ah nice work @shahabganji, I'm using Chrome on Windows 10 just for completeness.

**Comment by shahabganji** [comment]
You might not have any problem now, right ?

**Comment by freshcutdevelopment** [comment]
Thanks @shahabganji , yep all good now.

Cheers,
Sean
